[1.11.x] KOGITO-6929 spring-boot to 2.6.6 (#2120) (#2137)
* KOGITO-6929 spring-boot to 2.6.6 (#2120)

* KOGITO-6929 spring-boot to 2.6.6

* Spring Boot Cloud version update

* MongoDB upgrade

* Upgrade Keycloack

Co-authored-by: Cristiano Nicolai <570894+cristianonicolai@users.noreply.github.com>

* version.io.micrometer to 1.8.4 due to NoClassDefFoundError: io/micrometer/core/instrument/binder/system/DiskSpaceMetrics

* GHA workflow updated

Co-authored-by: Cristiano Nicolai <570894+cristianonicolai@users.noreply.github.com>