[1.24.x][KOGITO-7453][KOGITO-7546][KOGITO-7557][KOGITO-7625] - Error Handling Bug Fixing (#2351)
* KOGITO-7453: Add ExceptionHandlerPolicy implementation classes to extend error code evaluation (#2315)

* KOGITO-7453: Add ExceptionHandlerPolicy class that evaluates an error based on the exception message using contains or matches comparison

* KOGITO-7453: Add ExceptionHandlerPolicy class that verifies status code of javax.ws.rs.WebApplicationException response

* KOGITO-7453: Handle classloading error in WebApplicationExceptionPolicy

* KOGITO-7453: Create abstract parent class for common hierarchical exception traversal; handle NumberFormatException

* KOGITO-7543: Handle NoClassDefFoundError in test module; refactor WebApplicationExceptionPolicy

* KOGITO-7546: Improve regex handling in MessageContentExceptionPolicy (#2327)

* KOGITO-7546: Improve regex handling in MessageContentExceptionPolicy

* KOGITO-7546: Remove case insensitivity flag

* [KOGITO-7557] Refining WorkItemHandlerException handling (#2333)

* [KOGITO-7557] Defining new KogitoErrorCodeException

This exception will be used by WorkItemHandler interacting with REST
servers. It can also be reused for handlers interacting with external
service that return well known codes.

String is used as error code because it covers both numeric and
alphanumeric error codes

* [KOGITO-7557] Reusing WorkItemExecutionException

* [KOGITO-7557] Modifying engine handling

* [KOGITO-7557] Adding integrations test for error

* [KOGITO-7557] Review comments

* [KOGITO-7557] Refining

* [KOGITO-7557] Testing reusing same definition in several nodes

* [KOGITO-7557] Fixing boundary error failed tests

* [KOGITO-7557] Sonar bug

* [KOGITO-7557] Jan comments

* [KOGITO-7557] Restoring workitemhandler exception message

I do not like it, but it is not JIRA related, so, restoring

* [KOGITO-7557] Fixing bug reported by Marian

* [KOGITO-7557] Alternative approach based on exception scope

* [KOGITO-7557] Adding support for errors on parallel state

* KOGITO-7625 - Add ExceptionScope to native resource (#2348)

Co-authored-by: Martin Weiler <mweiler@redhat.com>
Co-authored-by: Cristiano Nicolai <570894+cristianonicolai@users.noreply.github.com>